#! /usr/bin/env bash

export TASK_X_ENV_PRECEDENCE=1 # https://github.com/go-task/task/issues/1038
# export TASK_X_MAP_VARIABLES=2  # https://taskfile.dev/experiments/map-variables/?proposal=2

go tool task "$@"
